# Generated by Django 2.0 on 2018-08-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bretzel',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
